server:
  port: 8056

spring:
  datasource:
    url: jdbc:mysql://119.29.221.146:3306/acstudent?useUnicode=true&allowMultiQueries=true
    username: root
    password: wsqMYSQL@2018
    driver-class-name: com.mysql.jdbc.Driver
  redis:
      host: 119.29.221.146
      port: 6369
      password: acstudent547
      database: 0
  profiles:
    active: dev

#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.douyu.wsd.reward.gift.common.domain
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #驼峰下划线转换
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

